apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "fluent-bit-dev-config"
data:
  fluent-bit.yaml: |
    plugins:
      - "/fluent-bit/plugins/out_clp_ir_file_linux_amd64.so"

    service:
      flush: 1
      daemon: "off"
      log_level: "trace"

    pipeline:
      inputs:
        - name: "tail"
          path: "/tmp/test-*.log"
          path_key: "file_path"
          tag: "michelangelo_logs"
          # The interval of refreshing the list of watched files in seconds
          refresh_interval: 5
          # For new discovered files on start (without a database offset/position),
          # read the content from the head of the file, not tail.
          read_from_head: true
          # Skips empty lines in the log file from any further processing or output
          skip_empty_lines: true
          # When a message is unstructured (no parser applied), it's appended as a string under the key
          # name log. This option allows to define an alternative name for that key.
          key: "message"
          processors: []

      outputs:
        - name: "out_clp_ir_file"
          match: "*"
          line_format: "json"
          log_bucket: "logs"