apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    app: "fluent-bit-dev"
  name: "fluent-bit-dev"
spec:
  containers:
    # Container which performs deployment once only
    # To inspect logs, use the following command; kubectl logs <pod> -c <container>
    - name: "fluent-bit-dev"
      image: "fluent/fluent-bit:3.2.7-debug"
      command:
        - "sh"
        - "-c"
        - "/fluent-bit/bin/fluent-bit --config /fluent-bit/etc/fluent-bit.yaml"
      env:
        - name: "AWS_ENDPOINT_URL"
          value: "http://minio:9000"
        - name: "AWS_REGION"
          value: "us-west-2"
      volumeMounts:
        - name: "aws-credentials-volume"
          mountPath: "/root/.aws"
        - name: "config-volume"
          mountPath: "/fluent-bit/etc"
        - name: "plugins-volume"
          mountPath: "/fluent-bit/plugins"
      imagePullPolicy: "IfNotPresent"
  volumes:
    - name: "aws-credentials-volume"
      secret:
        secretName: "aws-credentials"
    - name: "config-volume"
      configMap:
        name: "fluent-bit-dev-config"
    - name: "plugins-volume"
      hostPath:
        path: "/fluent-bit/plugins"
